export default [
  {
    id: 1,
    description:
      'Deniz kenarında huzurlu bir gün geçirdikten sonra ayaklarını uzatıp kafanı yukarı kaldırdığında gördüğün yıldızların keyfini çıkarırken ne kadar mutlu olduğunu düşün',
    date: '2025-06-02 11:00:00',
    likes: 150,
    commenta: 30,
    image: 'https://picsum.photos/1080/607',
    user: {
      name: 'Fırat ŞABAHAT',
      avatar: 'https://randomuser.me/api/portraits/men/85.jpg',
    },
  },
  {
    id: 2,
    description:
      'Ormanda yürüyüş ve temiz hava yaparken karşına çıkan en güzel ağacın sana verdiği huzuru yakaladığın zaman işte tam da o zaman hayatın ve içine çektiğin oksijenin ne kadar değerli olduğunu anlıyorsun ',
    date: '2025-06-03 14:20:00',
    likes: 235,
    commenta: 45,
    image: 'https://picsum.photos/1080/608',
    user: {
      name: 'Ayşe YILMAZ',
      avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
    },
  },
  {
    id: 3,
    description:
      'Kamp ateşi başında güzel bir sohbetten sonra gelen sıcacık bir uyku isteği ve yine aynı zamanda o sohbeti terkedemeyişin verdiği tatlı bir heyecan işte tüm bu duygular bizim tam da şuan da bulunduğumuz kamp ateşinin sizlere bir özeti olsun dostlar ',
    date: '2025-06-04 19:15:00',
    likes: 320,
    commenta: 55,
    image: 'https://picsum.photos/1080/609',
    user: {
      name: 'Mehmet DEMİR',
      avatar: 'https://randomuser.me/api/portraits/men/23.jpg',
    },
  },
  {
    id: 4,
    description: 'Gün batımında muhteşem manzara',
    date: '2025-06-05 09:30:00',
    likes: 210,
    commenta: 40,
    image: 'https://picsum.photos/1080/610',
    user: {
      name: 'Zeynep ÇELİK',
      avatar: 'https://randomuser.me/api/portraits/women/12.jpg',
    },
  },
  {
    id: 5,
    description: 'Sabah kahvesi ve kitap keyfi',
    date: '2025-06-06 22:00:00',
    likes: 189,
    commenta: 35,
    image: 'https://picsum.photos/1080/611',
    user: {
      name: 'Ali KAYA',
      avatar: 'https://randomuser.me/api/portraits/men/33.jpg',
    },
  },
  {
    id: 6,
    description: 'Yağmur sonrası gökkuşağı manzarası',
    date: '2025-06-07 16:45:00',
    likes: 275,
    commenta: 47,
    image: 'https://picsum.photos/1080/612',
    user: {
      name: 'Fatma AKSOY',
      avatar: 'https://randomuser.me/api/portraits/women/21.jpg',
    },
  },
  {
    id: 7,
    description: 'Kedimle sıcak bir pazar sabahı',
    date: '2025-06-08 10:20:00',
    likes: 330,
    commenta: 60,
    image: 'https://picsum.photos/1080/613',
    user: {
      name: 'Burak EREN',
      avatar: 'https://randomuser.me/api/portraits/men/45.jpg',
    },
  },
  {
    id: 8,
    description: 'Doğa içinde huzurlu bir kaçamak',
    date: '2025-06-09 15:15:00',
    likes: 180,
    commenta: 25,
    image: 'https://picsum.photos/1080/614',
    user: {
      name: 'Selin ARSLAN',
      avatar: 'https://randomuser.me/api/portraits/women/33.jpg',
    },
  },
  {
    id: 9,
    description: 'Bisiklet turunda harika anılar',
    date: '2025-06-10 17:50:00',
    likes: 245,
    commenta: 38,
    image: 'https://picsum.photos/1080/615',
    user: {
      name: 'Caner TUNÇ',
      avatar: 'https://randomuser.me/api/portraits/men/67.jpg',
    },
  },
  {
    id: 10,
    description: 'Yıldızların altında gece kampı',
    date: '2025-06-11 20:00:00',
    likes: 310,
    commenta: 52,
    image: 'https://picsum.photos/1080/616',
    user: {
      name: 'Elif ŞAHİN',
      avatar: 'https://randomuser.me/api/portraits/women/55.jpg',
    },
  },
  {
    id: 11,
    description: 'Karlı dağların arasında yolculuk',
    date: '2025-06-12 13:45:00',
    likes: 276,
    commenta: 41,
    image: 'https://picsum.photos/1080/617',
    user: {
      name: 'Efe YILDIZ',
      avatar: 'https://randomuser.me/api/portraits/men/77.jpg',
    },
  },
  {
    id: 12,
    description: 'Taze çiçeklerle dolu bir bahar',
    date: '2025-06-13 08:30:00',
    likes: 190,
    commenta: 29,
    image: 'https://picsum.photos/1080/618',
    user: {
      name: 'Aslıhan KURT',
      avatar: 'https://randomuser.me/api/portraits/women/61.jpg',
    },
  },
  {
    id: 13,
    description: 'Sahil kenarında gün doğumu',
    date: '2025-06-14 21:10:00',
    likes: 315,
    commenta: 57,
    image: 'https://picsum.photos/1080/619',
    user: {
      name: 'Onur GÜLTEKİN',
      avatar: 'https://randomuser.me/api/portraits/men/82.jpg',
    },
  },
  {
    id: 14,
    description: 'Rüzgarla dans eden sarı yapraklar',
    date: '2025-06-15 07:20:00',
    likes: 145,
    commenta: 20,
    image: 'https://picsum.photos/1080/620',
    user: {
      name: 'Merve TAŞ',
      avatar: 'https://randomuser.me/api/portraits/women/19.jpg',
    },
  },
  {
    id: 15,
    description: 'Bir fincan kahveyle sakin bir gün',
    date: '2025-06-16 23:45:00',
    likes: 360,
    commenta: 65,
    image: 'https://picsum.photos/1080/621',
    user: {
      name: 'Kerem ÇETİN',
      avatar: 'https://randomuser.me/api/portraits/men/92.jpg',
    },
  },
  {
    id: 16,
    description: 'Göl kenarında sabahın ilk ışıkları',
    date: '2025-06-17 06:30:00',
    likes: 198,
    commenta: 33,
    image: 'https://picsum.photos/1080/622',
    user: {
      name: 'Pelin ÖZTÜRK',
      avatar: 'https://randomuser.me/api/portraits/women/78.jpg',
    },
  },
  {
    id: 17,
    description: 'Şehirde sessiz bir akşam yürüyüşü',
    date: '2025-06-18 05:15:00',
    likes: 230,
    commenta: 44,
    image: 'https://picsum.photos/1080/623',
    user: {
      name: 'Cemil AKIN',
      avatar: 'https://randomuser.me/api/portraits/men/88.jpg',
    },
  },
  {
    id: 18,
    description: 'Müzik eşliğinde keyifli bir akşam',
    date: '2025-06-19 12:00:00',
    likes: 270,
    commenta: 48,
    image: 'https://picsum.photos/1080/624',
    user: {
      name: 'Ezgi POLAT',
      avatar: 'https://randomuser.me/api/portraits/women/45.jpg',
    },
  },
  {
    id: 19,
    description: 'Sanat galerisinde ilham dolu anlar',
    date: '2025-06-20 17:00:00',
    likes: 285,
    commenta: 50,
    image: 'https://picsum.photos/1080/625',
    user: {
      name: 'Levent ERSOY',
      avatar: 'https://randomuser.me/api/portraits/men/66.jpg',
    },
  },
  {
    id: 20,
    description: 'Çocukluk anıları gibi sıcak bir gün',
    date: '2025-06-21 15:45:00',
    likes: 310,
    commenta: 54,
    image: 'https://picsum.photos/1080/626',
    user: {
      name: 'Gizem AYDIN',
      avatar: 'https://randomuser.me/api/portraits/women/59.jpg',
    },
  },
];
